development:
  sessions:
    default:
      database: kc_comments_dev
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: kc_comments_test
      hosts:
        - localhost:27017